# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="xaptao"

# Disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Auto-update (in days).
export UPDATE_ZSH_DAYS=30

# Set custom folder location.
ZSH_CUSTOM=~/.dotfiles/zsh/custom

# Load plugins.
plugins=(git)

#
# User configuration.
#
export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"
export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
export PATH="$HOME/.composer/vendor/bin/:$PATH"
source $ZSH/oh-my-zsh.sh

# Manually set language environment.
export LANG=en_US.UTF-8

# Local and remote sessions editor.
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
fi

# This loads nvm.
export NVM_DIR="/Users/mike/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

#
# Virtualenvwrapper configuration.
#
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/dev/python
source /usr/local/bin/virtualenvwrapper.sh

# Set Pythonz.
[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc
