if [[ -r "${HOME}/.bashrc" ]]; then
	source "${HOME}/.bashrc"
fi

# Bash V3 is MacOS
# Bash > 4 installed with Brew (5.1)
# Bash completion V2 installed with Brew.
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

#
# Not used. For reference and to be deleted.
#
#export VIRTUALENVWRAPPER_PYTHON=/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
#export VIRTUALENVWRAPPER_VIRTUALENV=/Library/Frameworks/Python.framework/Versions/3.5/bin/virtualenv
#export WORKON_HOME=$HOME/.virtualenvs
#export PROJECT_HOME=$HOME/dev/python
#source /usr/local/bin/virtualenvwrapper.sh
#export PATH=$HOME/bin:/usr/local/bin:$PATH
#export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
# Ruby needed for Compass
#export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.0/bin:$PATH"
#export PATH="$HOME/.composer/vendor/bin:$PATH"
#export PATH="$PATH:$HOME/bin"
#export PATH="$HOME/.composer/vendor/bin:$PATH"
#export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Application paths: /etc/paths.d/

#
# Golang paths
#
export GOPATH="$HOME/go"
export GOBIN="$HOME/go/bin"

SYSPATH=$PATH
MYPATH=$HOME/bin:$GOBIN
#
# Set path priorities.
#
export PATH=$MYPATH:$SYSPATH