name: Slack notify

on: [push]

jobs:
  slack_call:
    runs-on: ubuntu-latest
    environment: github-slack
    steps:
      - env:
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.actor }} pushed code to ${{ github.ref_name }} "}' "$SLACK_URL"

