name: Slack notify

on: [push]

jobs:
  slack_call:
    runs-on: ubuntu-latest
    steps:
      - env:
        #SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

